version: "2"

services:
  mariadb:
    # image: wodby/mariadb:10.3-3.3.15
    # image: wodby/mariadb:10.2-3.3.15
    image: wodby/mariadb:10.1-3.3.15
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
# 1. Images with vanilla Drupal – wodby/drupal:[DRUPAL_VERSION]-[PHP_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal:8-7.1-4.11.0
#    image: wodby/drupal:8-7.0-4.11.0
#    image: wodby/drupal:7-7.1-4.11.0
#    image: wodby/drupal:7-7.0-4.11.0
#    image: wodby/drupal:7-5.6-4.11.0
#    image: wodby/drupal:6-5.6-4.11.0
#    image: wodby/drupal:6-5.3-4.11.0
# 2. Images without Drupal – wodby/drupal-php:[PHP_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-php:7.2-4.11.0
#    image: wodby/drupal-php:7.1-4.11.0
#    image: wodby/drupal-php:7.0-4.11.0
#    image: wodby/drupal-php:5.6-4.11.0
#    image: wodby/drupal-php:5.3-4.11.0
    user: root
    command: "php-fpm -R"
    environment:
      PHP_FPM_USER: root
      PHP_FPM_GROUP: root
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_REMOTE_HOST: host.docker.internal
#      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
#      PHP_XDEBUG_PROFILER_OUTPUT_DIR: /mnt/files/xdebug/profiler
#      PHP_XDEBUG_TRACE_OUTPUT_DIR: /mnt/files/xdebug/traces
    volumes:
       - ./:/var/www/html
## Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
#      - codebase:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
## For Xdebug profiler files
#      - files:/mnt/files

#   nginx:
##  wodby/nginx:[DRUPAL_VERSION]-[NGINX_VERSION]-[STABILITY_TAG].
#     image: wodby/nginx:1.15-3.0.1
##     image: wodby/nginx:1.14-3.0.1
##     image: wodby/nginx:1.13-3.0.1

#     depends_on:
#       - php
#     environment:
#       NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
#       NGINX_ERROR_LOG_LEVEL: debug
#       NGINX_BACKEND_HOST: php
#       NGINX_SERVER_ROOT: /var/www/html/web
#     volumes:
#       - ./:/var/www/html
# # Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
# #      - codebase:/var/www/html:cached # User-guided caching
# #      - docker-sync:/var/www/html # Docker-sync
#     labels:
#       - 'traefik.backend=nginx'
#       - 'traefik.port=80'
#       - 'traefik.frontend.rule=Host:cpr.docker.loc'

  apache:
    image: wodby/apache:2.4-4.0.3
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_VHOST_PRESET: php
      APACHE_BACKEND_HOST: php
      APACHE_BACKEND_PORT: 9000
      APACHE_DIRECTORY_INDEX: index.php
      APACHE_FCGI_PROXY_CONN_TIMEOUT: 5
      APACHE_FCGI_PROXY_TIMEOUT: 60
      APACHE_SERVER_ROOT: /var/www/html
      APACHE_DOCUMENT_ROOT: /var/www/html/web
    volumes:
      # - codebase:/var/www/html
      - ./:/var/www/html
 # Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
 #      - codebase:/var/www/html:cached # User-guided caching
 #      - docker-sync:/var/www/html # Docker-sync
    labels:
      - 'traefik.backend=apache'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:cpr.docker.localhost'

#  varnish:
#    image: wodby/drupal-varnish:6.0-4.2.0
#    image: wodby/drupal-varnish:4.1-4.2.0
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#    labels:
#      - 'traefik.backend=varnish'
#      - 'traefik.port=6081'
#      - 'traefik.frontend.rule=Host:varnish.cpr.docker.localhost'

#   redis:
#     image: wodby/redis:3.2-2.1.3
# ##    image: wodby/redis:4.0-2.1.3

  # adminer:
  #   image: wodby/adminer:4
  #   environment:
  #     ADMINER_SALT: adminer-salt
  #   labels:
  #     - 'traefik.backend=adminer'
  #     - 'traefik.port=9000'
  #     - 'traefik.frontend.rule=Host:adminer.cpr.docker.localhost'

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.cpr.docker.localhost'

#  solr:
## wodby/drupal-solr:[DRUPAL_VERSION]-[SOLR_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal-solr:8-6.6-2.2.0
##    image: wodby/drupal-solr:8-6.5-2.2.0
##    image: wodby/drupal-solr:8-6.4-2.2.0
##    image: wodby/drupal-solr:8-6.3-2.2.0
##    image: wodby/drupal-solr:8-5.5-2.2.0
##    image: wodby/drupal-solr:7-5.4-2.2.0
#    environment:
#      SOLR_HEAP: 1024m
#    labels:
#      - 'traefik.backend=solr'
#      - 'traefik.port=8983'
#      - 'traefik.frontend.rule=Host:solr.cpr.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.cpr.docker.localhost'

#  nodejs:
#    image: wodby/drupal-node:1.0-1.0.0
#    environment:
#       NODE_SERVICE_KEY: node-service-key
#    labels:
#      - 'traefik.backend=nodejs'
#      - 'traefik.port=8080'
#      - 'traefik.frontend.rule=Host:nodejs.cpr.docker.localhost'
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  node:
#    image: node:alpine
#    working_dir: /app
#    labels:
#      - 'traefik.backend=node'
#      - 'traefik.port=3000'
#      - 'traefik.frontend.rule=Host:front.cpr.docker.localhost'
#    expose:
#      - "3000"
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  memcached:
#    image: wodby/memcached:1.4-2.0.0

#  rsyslog:
#    image: wodby/rsyslog

#  athenapdf:
#    image: arachnysdocker/athenapdf-service:2.10.0
#    environment:
#      WEAVER_AUTH_KEY: weaver-auth-key
#      WEAVER_ATHENA_CMD: "athenapdf -S"
#      WEAVER_MAX_WORKERS: 10
#      WEAVER_MAX_CONVERSION_QUEUE: 50
#      WEAVER_WORKER_TIMEOUT: 90
#      WEAVER_CONVERSION_FALLBACK: false

#  blackfire:
#    image: blackfire/blackfire
#    environment:
#      BLACKFIRE_SERVER_ID: XXXXX
#      BLACKFIRE_SERVER_TOKEN: YYYYY

#  webgrind:
#    image: wodby/webgrind:1.5-1.0.0
#    environment:
#      WEBGRIND_PROFILER_DIR: /mnt/files/xdebug/profiler
#    labels:
#      - 'traefik.backend=webgrind'
#      - 'traefik.port=8080'
#      - 'traefik.frontend.rule=Host:webgrind.cpr.docker.localhost'
#    volumes:
#      - files:/mnt/files

  # portainer:
  #   image: portainer/portainer
  #   command: --no-auth -H unix:///var/run/docker.sock
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   labels:
  #     - 'traefik.backend=portainer'
  #     - 'traefik.port=9000'
  #     - 'traefik.frontend.rule=Host:portainer.cpr.docker.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# volumes:
  # codebase:./
## Docker-sync for macOS users
#  docker-sync:
#    external: true
## For Xdebug profiler
#  files:
